### ISSUE TITLE
Concatenation and support or data split over multiples files

### ISSUE THREAD

**Issue by rgrp** [openspending/fiscal-data-package#75] opened 2015-11-03 17:05 UTC
Copied from: https://github.com/openspending/osep/issues/30 (see also discussion there)

We currently have a use case to support situations where the data is spread over multiple files e.g.

```
budget1.csv
amount, date

budget2.csv
amount,data
```

It is also possible that "normalized" files e.g. payee information is also split over multiple csv files.

Rather than addressing this in the mapping by having to reference multiple files from each mapped attribute I propose that instead we have some way to indicate that files should be concatenated e.g. in mapping attribute or similar we have:

```
concatentations: [
  ["budget1.csv", "budget2.csv", ...],
  ["payee1.csv", "payee2.csv"]
]
```

I think this is a better solution because:

* It makes explicit the implicit assumption that these files have the same structure
* It is simpler to implement
* It keeps the mapping simple - you maps against the primary files e.g. budget1.csv or payee1.csv

**Comment by pwalsh** [comment] 2015-11-03 19:15
Still think my suggestion from the original thread is simpler. 

Copying in::

I thought about this more. I think we should *definitely* support the basic use case of multiple files of the "same" data, and we should do it as part of the core Tabular Data Package spec, on a `resource` object.

eg: given:

```
budget1.csv
amount, date

budget2.csv
amount,date
```

We would not have 2 distinct resources: rather, we'd allow `path`, `data` and `url` to be arrays:

```
{
  "name": "My Stuff",
  "resources": [
    {
      "path": ["budget1.csv", "budget2.csv"]
    }
  ]
}
```

I don't like having a distinct "concatenations" property: this pattern is a much better representation of the thing we are describing IMHO, and simply extends what already exists.

I agree that this is blurring a line between ETL and metadata. 

I think the pros outweigh the cons considering how common this really is out in the wild.

In the various libs that exist and will be further developed for dealing with DataPackages and resources therein, it is just trivial to extend iteration patterns over files to work on an array of them, or, perform some concat first and internally treat the files as one thing (`shutil.copyfileobj`, or whatever is behind `csvstack`, for example).

**Comment by rgrp** [comment] 2015-11-03 21:25
@pwalsh the issue this is a fundamental change to how Data Package works. I guess if they shared the same schema you could guess this - but it seems to me that you would really want to indicate this in the mapping rather than mess with the Tabular Data Package part.

**Comment by pwalsh** [comment] 2015-11-04 06:30
Ok, I understand it is a change, but not a great one IMHO (if name, url or path is an array, then it is an array of name, url or path values which implementations should treat as a single resource).

The reasons I think this is a reasonable and fundamentally useful approach is:

* There is a single implementation change: concat the data references in `name`, `url`, `path` if it is an array
* It is more DRY. Example: there is no *possibility* that someone writing a package could assign different schema to `budget1.csv` and `budget2.csv`, which would be possible in the `concatenations` approach
* It is explicit: the person creating a data package is forced to acknowledge: "this and that are the *same* resource, just split over multiple files". `concatenations` makes this muddier as on one hand, that is what the `concatenations` array suggestions, but the `resources` array suggests something different (they are distinct resources).

The reasons I think that the `concatenations` approach is confusing and open to error are:

* Implementation is much more convoluted. Code that handle the mapping, for each measure and dimension, needs to check if `source` is in `concatenations` and concat on a case by case basis
* Following from above: the implementing code will also have to ignore properties of the chained resources like `schema`, as the code *must* assume the schema is identical based on the `concatenations` declaration, and not on whatever is actually declared on the `schema` of that resource
* Human error: I can easily imagine scenarios where someone might map to `budget2` on a certain dimension and not to `budget1`: I expect an additional class of errors we'd have to handle in user interfaces that create FDP too, in additional to code that validates/models the spec itself.

Either way, I acknowledge that the suggestion is *controversial*, as it targets Tabular Data Package directly and is a clear step along an ETL path in the spec.

**Comment by rgrp** [comment] 2015-11-09 16:28
ACTION: @danfowler to open an issue on data protocols suggesting @pwalsh solution and we discuss there.

**Comment by danfowler** [comment] 2015-11-10 08:56
Closing as duplicate of https://github.com/dataprotocols/dataprotocols/issues/228

**Closed by danfowler** 2015-11-10 08:56 UTC
Labels: duplicate
