### ISSUE TITLE
Hierarchies for organisational structure, functional classifications, ... ?

### ISSUE THREAD

**Issue by stevage** [openspending/fiscal-data-package#55] opened 2015-10-01 03:06 UTC
(migrated from [OS forum](https://discuss.okfn.org/t/open-spending-data-structure-ideas-and-suggestions/300/24))

Why do we want to explicitly model organisational hierarchies?

* As a data consumer, I want to progressively dive into a dataset by aggregating it initially at levels I'm familiar with (federal departments) before discovering the internal structure of those departments.
* As a data storyteller, I want to use hierarchies in the visualisations that I build.

[For example](https://public.tableau.com/profile/steve.bennett#!/vizhome/AusBudget2015-16/AustralianFederalBudget2015-16):

**Comment by rgrp** [comment] 2015-11-03 17:02
@stevage the one question here is whether you want to do this is an *automated* way rather than have the visualization creator specify those hierarchies. Strictly you don't need this info in the data package unless you are going to use either to automate creating those visualizations or to guide the vis creation in some way.

Did you have either of these use cases in mind or will the vis creator choose the hierarchy themselves at vis creation time?

**Comment by stevage** [comment] 2015-11-07 12:34
I guess I'm hoping for tools that can be quite ignorant about the specifics of the data they're applied to - so yes, I was rather expecting an "automated way".

If information about hierarchies is not encoded in the data package, then it has to be encoded somewhere else - like, hard-coded in the data vis tool. ("When I load a Spanish economy file, I will treat fields X, Y and Z as a hierarchy.") That seems very suboptimal compared to simply recording it in the data package.

**Comment by pwalsh** [comment] 2015-11-07 18:34
Just in terms of the design of the hierarchy in FDP, the issue here is essentially the same as the one here https://github.com/openspending/fiscal-data-package/issues/48

My suggestion is that we all focus on the various and varied examples given there, get in a good, solid data structure for hierarchies on dimensions, and, solve this whole class of problems.

**Comment by rgrp** [comment] 2015-11-08 10:59
DUPLICATE of #48 - as per @pwalsh suggestion to merge.

@stevage on the general point: I think we will definitely implement support here but it is still worth thinking hard about how this actually gets used in tools as it helps us make really great choices here. Thank-you btw for all your engagement and great questions and suggestions here.

**Comment by rgrp** [comment] 2015-11-08 10:59
DUPLICATE of #48 - as per @pwalsh suggestion to merge.

@stevage on the general point: I think we will definitely implement support here but it is still worth thinking hard about how this actually gets used in tools as it helps us make really great choices here. Thank-you btw for all your engagement and great questions and suggestions here.

**Closed by rgrp** 2015-11-08 10:59 UTC
Labels: needs clarification
